# Generated by Django 5.0.6 on 2024-07-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lenguaje',
            old_name='lenguaje',
            new_name='nom_len',
        ),
    ]
